language: r

r:
  - release

install: 
  - R -e "install.packages(c('quantmod', 'jsonlite', 'magrittr', 'GetoptLong', 'tidyverse'))"
  
script:
  - R -e "source('gspc_rsi.R')"
  - R -e "source('prob_tree.R')"
  
deploy:
  provider: pages
  file: 
    - gspc.json
    - gspc.txt
    - gspc_pred.json
    - fear_greed.json
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
