language: r

r:
  - release

install: 
  - R -e "install.packages(c('quantmod', 'jsonlite', 'magrittr', 'GetoptLong'))"
  
script:
  - R -e "source('gspc_rsi.R')"

deploy:
  provider: pages
  file: 
    - gspc.json
    - gspc.txt
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
